# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from tavus_python_sdk import Tavus

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        tavus = Tavus(
        
                        api_key = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(tavus)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
