# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredReplicasGetReplicaByIdResponse(TypedDict):
    pass

class OptionalReplicasGetReplicaByIdResponse(TypedDict, total=False):
    # The date and time the replica was created.
    created_at: str

    # If the replica has an error, this will contain the error message.
    error_message: typing.Optional[str]

    # A unique identifier for the replica.
    replica_id: str

    # The name of the replica.
    replica_name: str

    # The status of the replica.
    status: str

    # A direct link to the video that will be used as the thumbnail for the replica.
    thumbnail_video_url: str

    # The progress of the replica training.
    training_progress: str

    # The date and time of when the replica was last updated.
    updated_at: str

class ReplicasGetReplicaByIdResponse(RequiredReplicasGetReplicaByIdResponse, OptionalReplicasGetReplicaByIdResponse):
    pass
