# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from tavus_python_sdk.type.videos_get_by_video_id_response_data import VideosGetByVideoIdResponseData

class RequiredVideosGetByVideoIdResponse(TypedDict):
    pass

class OptionalVideosGetByVideoIdResponse(TypedDict, total=False):
    # The date and time the video was created.
    created_at: str

    data: VideosGetByVideoIdResponseData

    # A direct link to download your generated video.
    download_url: str

    # A direct link to view your generated video, hosted by Tavus.
    hosted_url: str

    # The status of the video.
    status: str

    # A detailed status of the video.
    status_details: str

    # A direct link to stream your generated video.
    stream_url: str

    # The date and time of when the video was last updated.
    updated_at: str

    # A unique identifier for the video.
    video_id: str

class VideosGetByVideoIdResponse(RequiredVideosGetByVideoIdResponse, OptionalVideosGetByVideoIdResponse):
    pass
