# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from tavus_python_sdk.type.videos_get_all_response_data_item import VideosGetAllResponseDataItem

VideosGetAllResponseData = typing.List[VideosGetAllResponseDataItem]
