# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from tavus_python_sdk.paths.v2_replicas.post import CreateNewReplicaRaw
from tavus_python_sdk.paths.v2_replicas_replica_id.delete import DeleteByReplicaIdRaw
from tavus_python_sdk.paths.v2_replicas_replica_id.get import GetReplicaByIdRaw
from tavus_python_sdk.paths.v2_replicas.get import ListRaw
from tavus_python_sdk.paths.v2_replicas_replica_id_name.patch import RenameReplicaByIdRaw


class ReplicasApiRaw(
    CreateNewReplicaRaw,
    DeleteByReplicaIdRaw,
    GetReplicaByIdRaw,
    ListRaw,
    RenameReplicaByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
