# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from tavus_python_sdk.paths.v2_replicas.post import CreateNewReplica
from tavus_python_sdk.paths.v2_replicas_replica_id.delete import DeleteByReplicaId
from tavus_python_sdk.paths.v2_replicas_replica_id.get import GetReplicaById
from tavus_python_sdk.paths.v2_replicas.get import List
from tavus_python_sdk.paths.v2_replicas_replica_id_name.patch import RenameReplicaById
from tavus_python_sdk.apis.tags.replicas_api_raw import ReplicasApiRaw


class ReplicasApi(
    CreateNewReplica,
    DeleteByReplicaId,
    GetReplicaById,
    List,
    RenameReplicaById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ReplicasApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ReplicasApiRaw(api_client)
