# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from tavus_python_sdk.paths.v2_videos.post import CreateVideoFromReplicaAndScriptRaw
from tavus_python_sdk.paths.v2_videos_video_id.delete import DeleteByVideoIdRaw
from tavus_python_sdk.paths.v2_videos.get import GetAllRaw
from tavus_python_sdk.paths.v2_videos_video_id.get import GetByVideoIdRaw
from tavus_python_sdk.paths.v2_videos_video_id_name.patch import UpdateNameRaw


class VideosApiRaw(
    CreateVideoFromReplicaAndScriptRaw,
    DeleteByVideoIdRaw,
    GetAllRaw,
    GetByVideoIdRaw,
    UpdateNameRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
