# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from tavus_python_sdk.paths.v2_videos.post import CreateVideoFromReplicaAndScript
from tavus_python_sdk.paths.v2_videos_video_id.delete import DeleteByVideoId
from tavus_python_sdk.paths.v2_videos.get import GetAll
from tavus_python_sdk.paths.v2_videos_video_id.get import GetByVideoId
from tavus_python_sdk.paths.v2_videos_video_id_name.patch import UpdateName
from tavus_python_sdk.apis.tags.videos_api_raw import VideosApiRaw


class VideosApi(
    CreateVideoFromReplicaAndScript,
    DeleteByVideoId,
    GetAll,
    GetByVideoId,
    UpdateName,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VideosApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VideosApiRaw(api_client)
