# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import tavus_python_sdk
from tavus_python_sdk.model.replicas_get_replica_by_id_response import ReplicasGetReplicaByIdResponse
from tavus_python_sdk import configuration


class TestReplicasGetReplicaByIdResponse(unittest.TestCase):
    """ReplicasGetReplicaByIdResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
