# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import tavus_python_sdk
from tavus_python_sdk.model.videos_create_video_from_replica_and_script_response import VideosCreateVideoFromReplicaAndScriptResponse
from tavus_python_sdk import configuration


class TestVideosCreateVideoFromReplicaAndScriptResponse(unittest.TestCase):
    """VideosCreateVideoFromReplicaAndScriptResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
