# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from tavus_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from tavus_python_sdk.api_response import AsyncGeneratorResponse
from tavus_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from tavus_python_sdk import schemas  # noqa: F401

from tavus_python_sdk.model.videos_create_video_from_replica_and_script_request import VideosCreateVideoFromReplicaAndScriptRequest as VideosCreateVideoFromReplicaAndScriptRequestSchema
from tavus_python_sdk.model.videos_create_video_from_replica_and_script_response import VideosCreateVideoFromReplicaAndScriptResponse as VideosCreateVideoFromReplicaAndScriptResponseSchema

from tavus_python_sdk.type.videos_create_video_from_replica_and_script_response import VideosCreateVideoFromReplicaAndScriptResponse
from tavus_python_sdk.type.videos_create_video_from_replica_and_script_request import VideosCreateVideoFromReplicaAndScriptRequest

from ...api_client import Dictionary
from tavus_python_sdk.pydantic.videos_create_video_from_replica_and_script_response import VideosCreateVideoFromReplicaAndScriptResponse as VideosCreateVideoFromReplicaAndScriptResponsePydantic
from tavus_python_sdk.pydantic.videos_create_video_from_replica_and_script_request import VideosCreateVideoFromReplicaAndScriptRequest as VideosCreateVideoFromReplicaAndScriptRequestPydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = VideosCreateVideoFromReplicaAndScriptRequestSchema


request_body_videos_create_video_from_replica_and_script_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)
_auth = [
    'apiKey',
]
SchemaFor200ResponseBodyApplicationJson = VideosCreateVideoFromReplicaAndScriptResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: VideosCreateVideoFromReplicaAndScriptResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: VideosCreateVideoFromReplicaAndScriptResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_video_from_replica_and_script_mapped_args(
        self,
        replica_id: str,
        script: str,
        background_source_url: typing.Optional[str] = None,
        background_url: typing.Optional[str] = None,
        video_name: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if background_source_url is not None:
            _body["background_source_url"] = background_source_url
        if background_url is not None:
            _body["background_url"] = background_url
        if replica_id is not None:
            _body["replica_id"] = replica_id
        if script is not None:
            _body["script"] = script
        if video_name is not None:
            _body["video_name"] = video_name
        args.body = _body
        return args

    async def _acreate_video_from_replica_and_script_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Generate Video
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v2/videos',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_videos_create_video_from_replica_and_script_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_video_from_replica_and_script_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Generate Video
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v2/videos',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_videos_create_video_from_replica_and_script_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateVideoFromReplicaAndScriptRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_video_from_replica_and_script(
        self,
        replica_id: str,
        script: str,
        background_source_url: typing.Optional[str] = None,
        background_url: typing.Optional[str] = None,
        video_name: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_video_from_replica_and_script_mapped_args(
            replica_id=replica_id,
            script=script,
            background_source_url=background_source_url,
            background_url=background_url,
            video_name=video_name,
        )
        return await self._acreate_video_from_replica_and_script_oapg(
            body=args.body,
            **kwargs,
        )
    
    def create_video_from_replica_and_script(
        self,
        replica_id: str,
        script: str,
        background_source_url: typing.Optional[str] = None,
        background_url: typing.Optional[str] = None,
        video_name: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_video_from_replica_and_script_mapped_args(
            replica_id=replica_id,
            script=script,
            background_source_url=background_source_url,
            background_url=background_url,
            video_name=video_name,
        )
        return self._create_video_from_replica_and_script_oapg(
            body=args.body,
        )

class CreateVideoFromReplicaAndScript(BaseApi):

    async def acreate_video_from_replica_and_script(
        self,
        replica_id: str,
        script: str,
        background_source_url: typing.Optional[str] = None,
        background_url: typing.Optional[str] = None,
        video_name: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> VideosCreateVideoFromReplicaAndScriptResponsePydantic:
        raw_response = await self.raw.acreate_video_from_replica_and_script(
            replica_id=replica_id,
            script=script,
            background_source_url=background_source_url,
            background_url=background_url,
            video_name=video_name,
            **kwargs,
        )
        if validate:
            return VideosCreateVideoFromReplicaAndScriptResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(VideosCreateVideoFromReplicaAndScriptResponsePydantic, raw_response.body)
    
    
    def create_video_from_replica_and_script(
        self,
        replica_id: str,
        script: str,
        background_source_url: typing.Optional[str] = None,
        background_url: typing.Optional[str] = None,
        video_name: typing.Optional[str] = None,
        validate: bool = False,
    ) -> VideosCreateVideoFromReplicaAndScriptResponsePydantic:
        raw_response = self.raw.create_video_from_replica_and_script(
            replica_id=replica_id,
            script=script,
            background_source_url=background_source_url,
            background_url=background_url,
            video_name=video_name,
        )
        if validate:
            return VideosCreateVideoFromReplicaAndScriptResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(VideosCreateVideoFromReplicaAndScriptResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        replica_id: str,
        script: str,
        background_source_url: typing.Optional[str] = None,
        background_url: typing.Optional[str] = None,
        video_name: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_video_from_replica_and_script_mapped_args(
            replica_id=replica_id,
            script=script,
            background_source_url=background_source_url,
            background_url=background_url,
            video_name=video_name,
        )
        return await self._acreate_video_from_replica_and_script_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        replica_id: str,
        script: str,
        background_source_url: typing.Optional[str] = None,
        background_url: typing.Optional[str] = None,
        video_name: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_video_from_replica_and_script_mapped_args(
            replica_id=replica_id,
            script=script,
            background_source_url=background_source_url,
            background_url=background_url,
            video_name=video_name,
        )
        return self._create_video_from_replica_and_script_oapg(
            body=args.body,
        )

