# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ReplicasListResponseDataItem(BaseModel):
    created_at: typing.Optional[str] = Field(None, alias='created_at')

    # A unique identifier for the replica.
    replica_id: typing.Optional[str] = Field(None, alias='replica_id')

    # The name of the replica.
    replica_name: typing.Optional[str] = Field(None, alias='replica_name')

    # The status of the replica.
    status: typing.Optional[str] = Field(None, alias='status')

    # A direct link to the video that will be used as the thumbnail for the replica.
    thumbnail_video_url: typing.Optional[str] = Field(None, alias='thumbnail_video_url')

    # The progress of the replica training.
    training_progress: typing.Optional[str] = Field(None, alias='training_progress')
    class Config:
        arbitrary_types_allowed = True
