# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class VideosCreateVideoFromReplicaAndScriptResponse(BaseModel):
    # The date and time the video was created.
    created_at: typing.Optional[str] = Field(None, alias='created_at')

    # A direct link to view your video once generation has completed, hosted by Tavus.
    hosted_url: typing.Optional[str] = Field(None, alias='hosted_url')

    # The status of the video.
    status: typing.Optional[str] = Field(None, alias='status')

    # A unique identifier for the video.
    video_id: typing.Optional[str] = Field(None, alias='video_id')

    # The name of the video.
    video_name: typing.Optional[str] = Field(None, alias='video_name')
    class Config:
        arbitrary_types_allowed = True
