# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from tavus_python_sdk.pydantic.videos_get_by_video_id_response_data import VideosGetByVideoIdResponseData

class VideosGetByVideoIdResponse(BaseModel):
    # The date and time the video was created.
    created_at: typing.Optional[str] = Field(None, alias='created_at')

    data: typing.Optional[VideosGetByVideoIdResponseData] = Field(None, alias='data')

    # A direct link to download your generated video.
    download_url: typing.Optional[str] = Field(None, alias='download_url')

    # A direct link to view your generated video, hosted by Tavus.
    hosted_url: typing.Optional[str] = Field(None, alias='hosted_url')

    # The status of the video.
    status: typing.Optional[str] = Field(None, alias='status')

    # A detailed status of the video.
    status_details: typing.Optional[str] = Field(None, alias='status_details')

    # A direct link to stream your generated video.
    stream_url: typing.Optional[str] = Field(None, alias='stream_url')

    # The date and time of when the video was last updated.
    updated_at: typing.Optional[str] = Field(None, alias='updated_at')

    # A unique identifier for the video.
    video_id: typing.Optional[str] = Field(None, alias='video_id')
    class Config:
        arbitrary_types_allowed = True
