# coding: utf-8

"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import tavus_python_sdk
from tavus_python_sdk.paths.v2_videos_video_id_name import patch
from tavus_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV2VideosVideoIdName(ApiTestMixin, unittest.TestCase):
    """
    V2VideosVideoIdName unit test stubs
        Rename Video
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''


if __name__ == '__main__':
    unittest.main()
