# coding: utf-8
"""
    Tavus Developer API Collection

    We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from tavus_python_sdk.client_custom import ClientCustom
from tavus_python_sdk.configuration import Configuration
from tavus_python_sdk.api_client import ApiClient
from tavus_python_sdk.type_util import copy_signature
from tavus_python_sdk.apis.tags.replicas_api import ReplicasApi
from tavus_python_sdk.apis.tags.videos_api import VideosApi



class Tavus(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.replicas: ReplicasApi = ReplicasApi(api_client)
        self.videos: VideosApi = VideosApi(api_client)
